PARTIE_SOLO = 100
PARTIE_DUO = 101
PARTIE_EN_LIGNE = 102

LARGEUR_PLATEAU = 20
HAUTEUR_PLATEAU = 15

LARGEUR_FENETRE = LARGEUR_PLATEAU * 32
HAUTEUR_FENETRE = HAUTEUR_PLATEAU * 32

CRAPAUD_1 = 1
CRAPAUD_2 = 2

CASE_MOUVEMENT = "M"
CASE_POINT_EMPTY = "P"
CASE_POINT_GAINED = "G"